### ISSUE TITLE
Introducing futures/1.0.2 is not a bugfix release

### ISSUE THREAD

**Issue by mknecht** [davidaurelio/hashids-python#11]
Hey,

we just upgraded from 1.0.1 to 1.0.2, and ran into this bug with [New Relic](https://discuss.newrelic.com/t/attributeerror-httpsconnection-instance-has-no-attribute--nr-external-tracer/15759).

`AttributeError: HTTPSConnection instance has no attribute '_nr_external_tracer'

Arguably, introducing the future-dependency was not a bugfix change, since it must be expected to change other code in a non-backwards-compatible manner.

I know you can't do anything about this anymore, since 1.0.2 is published, but I thought I'd document it for others to find. :)

Cheers,
murat

**Comment by davidaurelio** [comment]
Thank you for reporting! I’m really sorry that I have been causing trouble.

You are completely right, I *wanted* to release version v1.1.0, but on the other hand I also wanted to sync versions with the original JavaScript implementation as well. I probably took the wrong decision.

If it helps, I will be happy to release v1.0.3 that works without future, since I’m only using `past.builtins.basestring` anyways. Would that solve your problem?

**Comment by mknecht** [comment]
@davidaurelio well, it's a tricky bug. :) A 1.0.3 would be great; we could then kick out the library again, and remove the hotfix.

Btw, there was no tag for 1.0.2. Maybe you did not push it.

**Comment by davidaurelio** [comment]
I’ve just pushed v1.0.3 to PyPI. Could you check out whether it works for you? It removes the dependency to future and brings back the old `basestring`/`str` test.

**Comment by davidaurelio** [comment]
@mknecht Did v1.0.3 help? Care to close?

**Comment by mknecht** [comment]
@davidaurelio I updated us to 1.0.3 and could remove the future dependency, thus freeing us from the new-relic bugfix. \o/

Closing, thank you!

**Comment by davidaurelio** [comment]
Great, thank you!
