### ISSUE TITLE
Generate hashid using string as input

### ISSUE THREAD

**Issue by fabiocaccamo** [davidaurelio/hashids-python#30]
Is it possible to create a short unique hashid from a string?

I need to generate a short id from uuid like `2b8b9396-0cdf-4b9c-a03d-b25e1d93601b`

**Comment by thedrow** [comment]
A UUID can be represented by an [integer](https://docs.python.org/3.7/library/uuid.html#uuid.UUID.int) or a [tuple of integers](https://docs.python.org/3.7/library/uuid.html#uuid.UUID.fields).

Never convert UUIDs to strings unless you really have to.

**Comment by pjdon** [comment]
@fabiocaccamo If you are generating a shorter id from a larger string, won't that break the one-to-one assumption of encode/decode since multiple uuids will map to the same id.

**Comment by fabiocaccamo** [comment]
@pmsoltani I understand the *security reasons*, but I think that security is a problem of the developers and not of this library. 
If a developer stores a password in plain text or using `hashid` it is no longer a problem of the framework neither of the library.

For example, in `django` if you have a model where the primary key is a `uuid`, you could need to `hashid` it if you don't wont to expose it directly, so this feature would be just a plus.

---

@pjdon don't forget that a `uuid` is an hex string and contains only `a-f0-9` characters.

**Comment by pjdon** [comment]
@fabiocaccamo That's a good point, the uuid can be shortened. But, you then have to supply a description of the input format to the encoder.

I guess you've already solved the problem, you can convert the uuid to a unique integer and hash and id from that.

**Comment by fabiocaccamo** [comment]
@pjdon why you should supply the input format? A 36 or 32 (without `-`) chars length hex string could be easily detected using a `RegExp`.

**Comment by pjdon** [comment]
@fabiocaccamo I deleted my comment because I realized I had nothing substantial to add.

You would have to pass a regexp to the encoder so that it knows to ignore the dashes and treat each character as a hex. I think string conversion is *useful* but it's too much overhead for the devs, and taking only integers is a better entry point.

**Comment by pmsoltani** [comment]
@fabiocaccamo I understand your point, but unfortunately, not everyone knows enough about security to even know that they are doing something unsafe. Hence, I agree with the developers' decision.

Regarding the use case you mentioned:
> For example, in `django` if you have a model where the primary key is a `uuid`, you could need to `hashid` it if you don't wont to expose it directly, so this feature would be just a plus.

As I understand it, exposing the primary key can be a bad choice, usually because it may leak internal business logic to the users; e.g. `http://example.com/checkout?order=1223`, from which an attentive user can infer some information about the size of the business. But `UUID` is obscure enough and does not have the weakness mentioned, so why not expose it?

**Comment by davidaurelio** [comment]
@fabiocaccamo Sorry for never responding here. I will not add any additions that aren’t generally supported by other implementations.

Since a UUID is basically a 128bit number, you could pass it as suggested by @thedrow. 

Thoughts? I will close this for now.

**Comment by TechComet** [comment]
`print(Hashids('Enter string here').encode(1, 2, 3))`
